#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=4:00:00
#PBS -N eddy
#PBS -l vmem=16gb
#PBS -V


# needs mrtrix3 container for eddy_openmp
export SINGULARITYENV_OMP_NUM_THREADS=$OMP_NUM_THREADS

time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./eddy-bl.sh
time singularity exec -e docker://brainlife/fsl:6.0.1 ./eddy_qc.sh
